config: 1.0
messages:
  setmax-usage: "&cYou need to follow the usage: /maxplayers <number|reload>"
  num-done: "&cThe number of the players who can join the server is now &e%num%"
  no-num: "&cThis is not a number so please follow the usage\n&eYou need to follow the usage: /maxplayers <number|reload>"
  no-permission: "&cYou dont have permission to that command!"
  config-reload: "&aConfig reloaded"
  ## Number change ##
num: 33